---
- block:
   - name: Install nginx apt
     become: true
     ansible.builtin.apt:
       name: 
         - nginx
         - git
       state: present
       update_cache: yes
  rescue:
   - name: Install epel
     become: true
     yum:
       name: 
       - epel-release
       state: present
   - name: Install nginx
     become: true
     yum:
       name:
       - nginx
       - git
       state: present
- name: Getting lighthouse from repo 
  become: true
  git:
    repo: "{{ lighthouse_repo }}"
    version: master
    dest: "{{ lighthouse_loc_dir }}"
  register: copy_remote
- name: Make nginx config
  become: true
  template:
     src: template/lighthouse.j2
     dest: /etc/nginx/conf.d/default.conf
     mode: 0644
  notify: Start nginx service
